apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: psmdb
  namespace: database
spec:
  crVersion: 1.14.0
  image: percona/percona-server-mongodb:5.0.14-12
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: disabled
    schedule: "0 2 * * *"
  secrets:
    users: psmdb-secrets
  replsets:
    - name: rs0
      size: 1
      affinity:
        antiAffinityTopologyKey: "none"
      podDisruptionBudget:
        maxUnavailable: 1
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: longhorn
          resources:
            requests:
              storage: 3Gi
      resources:
        requests:
          cpu: 1000m
          memory: 2G
        limits:
          cpu: 2000m
          memory: 4G
    - name: rs1
      size: 1
      affinity:
        antiAffinityTopologyKey: "none"
      podDisruptionBudget:
        maxUnavailable: 1
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: longhorn
          resources:
            requests:
              storage: 3Gi
      resources:
        requests:
          cpu: 1000m
          memory: 2G
        limits:
          cpu: 2000m
          memory: 4G

  sharding:
    enabled: true
    configsvrReplSet:
      size: 2
      affinity:
        antiAffinityTopologyKey: "none"
      podDisruptionBudget:
        maxUnavailable: 1
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: longhorn
          resources:
            requests:
              storage: 1Gi
      resources:
        requests:
          cpu: 500m
          memory: 1G
        limits:
          cpu: 1000m
          memory: 2G

    mongos:
      size: 1
      affinity:
        antiAffinityTopologyKey: "none"
      resources:
        requests:
          cpu: 1000m
          memory: 1G
        limits:
          cpu: 2000m
          memory: 2G
