apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synapse-tls-manual
  namespace: default
spec:
  secretName: synapse-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - matrix.dev.tese.io 